services:
  - type: web
    name: blog-with-users
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: blog_db
          property: connectionString

databases:
  - name: blog_db
    databaseName: blog_db
    user: blog_db

